version: '3.9'
name: 'rinha-de-backend'

#  1.5 CPUs = 0.7 MongoDB + 2 x 0.35 Spring Boot + 0.05 NGinx
#    3.0 GB = 0.65 MongoDB + 2 x 1.10 Spring Boot +  0.10 NGinx

services:
  spring-api1:
#    image: boaglio/rinhabackend2023:latest
    image: docker.io/library/rinhabackend2023:0.0.1-SNAPSHOT
    hostname: spring-api1
    environment:
      - SERVER_PORT=8080
      - MONGO_URI=mongodb://db-mongodb:27017/rinhadb?socketTimeoutMS=360000&connectTimeoutMS=360000&maxPoolSize=50&minPoolSize=50
      - REDIS_HOST=cache
    depends_on:
      - db-mongodb
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.1GB'
    networks:
      - app-network

  spring-api2:
    #    image: boaglio/rinhabackend2023:latest
    image: docker.io/library/rinhabackend2023:0.0.1-SNAPSHOT
    hostname: spring-api2
    environment:
      - SERVER_PORT=8080
      - MONGO_URI=mongodb://db-mongodb:27017/rinhadb?socketTimeoutMS=360000&connectTimeoutMS=360000&maxPoolSize=50&minPoolSize=50
      - REDIS_HOST=cache
    depends_on:
      - db-mongodb
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.1GB'
    networks:
        - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api1
      - spring-api2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.1GB'

  db-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '0.65GB'
    networks:
      - app-network

networks:
  app-network: