version: '3.9'

services:
  db-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.5GB'
    networks:
      - app-network

  cache:
    hostname: cache
    image: redis:latest
    command: ["redis-server", "--appendonly", "no", "--save ''"]
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.25GB'
    networks:
      - app-network

networks:
  app-network: