version: '3.9'

services:
  db-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1GB'
    networks:
      - app-network

  cache:
    hostname: cache
    image: redis:latest
    command: redis-server --save "" --appendonly no
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.25GB'
    networks:
      - app-network

networks:
  app-network: