version: '3.9'

services:
  db-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '0.7GB'
    networks:
      - app-network

networks:
  app-network: